[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
app = { path = "../app", features = [] }
portal = { path = "../", features = ["bindings"] }
tokio = { version = "1.41.1", features = [] }