[package]
name = "sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
portal = { path = "../" }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }